spring.application.name=libraff-book-store

server.port=8080

spring.datasource.url=jdbc:h2:mem:db
spring.datasource.username=root
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace


spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.root=WARN
spring.output.ansi.enabled=ALWAYS

resilience4j.ratelimiter.instances.restockBook.limitForPeriod=5
resilience4j.ratelimiter.instances.restockBook.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.restockBook.timeoutDuration=0

resilience4j.ratelimiter.instances.employeeController.limitForPeriod=5
resilience4j.ratelimiter.instances.employeeController.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.employeeController.timeoutDuration=0

app.rateLimitPerMinute=5